spring.datasource.url=jdbc:sqlite:bookexchange.db
spring.datasource.driver-class-name=org.sqlite.JDBC
# критично принудительно запускает
spring.sql.init.mode=always 
spring.sql.init.continue-on-error=true
server.port=5000

# комментарий важный ключевой
jwt.secret=ThisIsMySuperSecureAndVeryVeryLongSecretKeyForBookExchangeHS512Algorithm
jwt.expiration-in-ms=900000

# комментарий важный ключевой
app.jwtRefreshExpirationMs=2592000000

# оставить включенным для
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG

# отключаем кэширование статических
spring.web.resources.cache.period=0

# критично отключаем обработку
spring.web.resources.add-mappings=false

# игнорируем конце важный
spring.mvc.trailing-slash=false