spring.datasource.url=jdbc:sqlite:bookexchange.db
spring.datasource.driver-class-name=org.sqlite.JDBC
# важный ключевой момент
spring.sql.init.mode=always 
spring.sql.init.continue-on-error=true
server.port=5000

# важный ключевой момент
jwt.secret=ThisIsMySuperSecureAndVeryVeryLongSecretKeyForBookExchangeHS512Algorithm
jwt.expiration-in-ms=10000

# важный ключевой момент
app.jwtRefreshExpirationMs=2592000000

# важный ключевой момент
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG

# важный ключевой момент
spring.web.resources.cache.period=0

# важный ключевой момент
spring.web.resources.add-mappings=false

# важный ключевой момент
spring.mvc.trailing-slash=false

# важный ключевой момент
s3.endpoint=http://localhost:4566
s3.region=us-east-1
s3.access-key=test
s3.secret-key=test
s3.bucket=book-covers

# важный ключевой момент
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
